### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by ghost** [jameshadfield/phandangoExampleData#1]
@jameshadfield , could you please help me show my ml tree with annotation, thanks. :)

**Comment by jameshadfield** [comment]
Sure. Just visit phandango.net and drag your files (ml tree, annotation CSV) onto the browser. Full instructions are here: https://github.com/jameshadfield/phandango/wiki.

best, james

**Comment by ghost** [comment]
@jameshadfield could you please help me show my tree, please, my tree is nexus, and when I drag it into the browser, it reported error. Thanks.

**Comment by jameshadfield** [comment]
Here's the relevant quote from the instructions linked above

>Trees must be in Newick format and must end in .tre or .tree (example here). Newick is the standard output from most tree drawing software (e.g. RAxML), but not all. If you need to convert your tree to a different format try using FigTree but watch out - often single quotations are added around taxon names which must be manually removed! Regrettably Nexus files are not currently supported.

https://github.com/jameshadfield/phandango/wiki/Input%20data%20formats#phylogenies-trees

**Comment by ghost** [comment]
My tree is in nexus format with bootstrap value, is there any software or script that can convert my tree into newick format with bootstrap value,thanks. :)

**Comment by jameshadfield** [comment]
From the above quote:

> If you need to convert your tree to a different format try using FigTree but watch out - often single quotations are added around taxon names which must be manually removed!

**Comment by ghost** [comment]
@jameshadfield, could you please help me annotate my phyml tree please, if so, I will send my data to you.
Thanks.
