### ISSUE TITLE
error in phandango file

### ISSUE THREAD

**Issue by ghazalaziz** [jameshadfield/phandangoExampleData#3]
I am trying to input roaory tree newick file on phANDANGO BUT IT IS CAUSING ERROR

Input error. File: Galaxy68-[Roary_on_data_60,_data_59,_and_others_Accessory_Binary_Genes_(Newick)].nhx
Error: Unknown file extension (nhx)

**Comment by jameshadfield** [comment]
Can you try renaming your tree file suffix to `.newick` or `.tre`, like the example trees in this repo?

**Comment by ghazalaziz** [comment]
yes it worked thank You
