### ISSUE TITLE
Error for Roary input data

### ISSUE THREAD

**Issue by vappiah** [jameshadfield/phandangoExampleData#4]
Dear @jameshadfield 
I tried analyzing roary gene_presence_absence file on the phandango page and the message  i got was
_Blocks provided without a tree, so this data cannot be displayed!_

Please advice

Thanks.

**Comment by jameshadfield** [comment]
You'll need to drag on a tree whose tips match the samples in the roary file. See [here](https://github.com/jameshadfield/phandangoExampleData/tree/master/roary_S.Weltevreden) for some example files and [the docs](https://github.com/jameshadfield/phandango/wiki) for more info.

**Comment by vappiah** [comment]
I got the same error message with the example data that you specified. Attached is a screenshot of the error message.
![Screenshot from 2024-02-01 21-13-18](https://github.com/jameshadfield/phandangoExampleData/assets/14283733/ca06f16a-0e4f-470b-9293-ed86add3a719)

**Comment by jameshadfield** [comment]
When I drag on the files `gene_presence_absence.csv` and `sw_chr_gubbins.tre` everything is working as expected:

<img width="848" alt="image" src="https://github.com/jameshadfield/phandangoExampleData/assets/8350992/c7ab5c2f-1fdd-4774-ab1a-fda7da41ce1c">


A few ideas to try to debug things on your setup:
* Go to phandango.net, click on "example data" then click on the image under "ROARY pan-genome". This should correctly load the data for you and helps check that phandango is working correctly in your browser.
* In a new phandango window, drag on your files (or drag on the example files) and check the browser console for any more detailed error messages
* Ensure your operating system is not adding on different file-name suffixes to your files, which may be hidden from you when browsing the files

**Comment by vappiah** [comment]
I got it now. I have to drag both the tree and the gene presence absence file and it works.

Thanks
